primaryColor=#36a9e1
secondaryColor=#86C953
labelColor=#ffffff
hideWhenOffline=1
contactMail=admin@domain.com
loadingLabel=Loading...
loginError=Can't login
chatHeader=Talk to us
startInfo=Please fill the following form to start the chat
startLabel=Start
backLabel=Back
initMessageBody=Hello, how may I help you?
initMessageAuthor=Operator
chatInputLabel=Write your question
timeDaysAgo=day(s) ago
timeHoursAgo=hour(s) ago
timeMinutesAgo=minute(s) ago
timeSecondsAgo=second(s) ago
offlineMessage=Operator went off-line
toggleSoundLabel=Sound effects
toggleScrollLabel=Auto-scroll
toggleEmoticonsLabel=Emoticons
toggleAutoShowLabel=Auto-show
contactHeader=Contact us
contactInfo=All operators are off-line. Use the below form to send us an e-mail with your question.
contactNameLabel=Your name
contactMailLabel=Your e-mail
contactQuestionLabel=Your question
contactSendLabel=Send
contactSuccessHeader=Message sent
contactSuccessMessage=Your question has been sent. Thank you!
contactErrorHeader=Error
contactErrorMessage=There was an error sending your question
maxConnections=5
messageSound=audio/default.mp3
installed=1
